### ISSUE TITLE
Question: API Specs?

### ISSUE THREAD

**Issue by miquelbeltran** [littleyoda/Home-Assistant-Tripower-X-MQTT#1]
Hi @littleyoda I've been exploring your project, and I see that you call to the login URL `'http://' + cfg["InverterAdress"] + '/api/v1/token'` passing some post data. Which doesn't seem to work for me, as my device returns an error with status code 400. I have a Sunny Tripower X 12.

Anyway, what I am curious to know is where did you get this API spec from? It does not look like the one found in https://developer.sma.de/sma-apis.html

**Comment by littleyoda** [comment]
I have reverse engineered the API. I have recorded the traffic that occurs when I access the inverter directly with the browser.

To test:
- please verify with a browser that the username + password are really correct.
- Start the developer tools in your browser and activate network analysis. The first post request after clicking on Login should be interesting. 

I'm using a Tripower X 15. 
Firmware-Version 02.06.04.R 

If you don't get it solved, I would need the traffic of the login process:
https://support.zendesk.com/hc/en-us/articles/4408828867098-Generating-a-HAR-file-for-troubleshooting


Translated with www.DeepL.com/Translator (free version)

**Comment by miquelbeltran** [comment]
Thanks for the quick response! I will keep investigating, I haven't thought about checking the browser connection.

**Comment by miquelbeltran** [comment]
btw, it was a wrong user/pass, the 400 response got me confused (I'd have expected a 401)

**Comment by miquelbeltran** [comment]
One last message, I got the whole solution working! Only had to create one template on HA to take the total Wh output and convert it to kWh. Thanks a lot for sharing your work ;)
