### ISSUE TITLE
will this work for tripower-Smart Energy devices? 

### ISSUE THREAD

**Issue by christf** [littleyoda/Home-Assistant-Tripower-X-MQTT#8]
thank you for this great work! I wish the data would be in mqtt from the start.
Are these devices supported too? Unfortunately I cannot see if they run ennexOS.

**Comment by littleyoda** [comment]
As far as I know, the following devices are ennexOS based:
Tripower X
Sunny Boy Smart Energy
SMA Charger

But if you are using HomeAssistant, take a look at my new integration.
https://github.com/littleyoda/ha-pysmaplus

It is easy to use and more devices (not only ennexOS-based) are supported.

**Comment by christf** [comment]
I am not a ha user but do utilize mqtt. So if those devices can somehow be scraped and the data exported to mqtt this would already do the deed.
The rest is influxdb and node-red....

**Comment by littleyoda** [comment]
I'm not quite sure which device you have.
If you have one of the devices listed, this solution should work without any problems.

**Comment by christf** [comment]
Apologies, I should have linked that in the first post. https://www.sma.de/produkte/solar-wechselrichter/sunny-tripower-80-100

I can't see what os it is running, hence the question

**Comment by littleyoda** [comment]
no enneox devices.

You can try the following script from me:
https://github.com/littleyoda/pysma/tree/master/scripts/pysma2mqtt

You can try webconnect and/or speedwire as interface.

**Comment by sushymediatech** [comment]
@christf when you run node red anyway can't you read the values from the inverter via modbus? once read you can send to your mqtt server or store to influxdb directly.

**Comment by christf** [comment]
I didn't get modbus to work in a stable way, hence using we connect from node-red.
